image:
- Ubuntu1804
- Visual Studio 2019

clone_depth: 50

pull_requests:
  do_not_increment_build_number: true
  

skip_commits:
  files:
    - docs/*
    - assets/*
    - LICENSE
    - mkdocs.yml
    - README.md
    - .travis.yml
    - .gitignore
    - lang/*
for:
-
  matrix:
    only:
      - image: Visual Studio 2019


  install:
  #- ps: cd c:\projects\xxx
                
  before_build:
  - ps: dotnet tool install --global FlubuCore.GlobalTool --version 5.0.3

  build_script:
  - ps: cd src
  - ps: flubu Rebuild

-
  matrix:
    only:
      - image: Ubuntu1804
    
  before_build:
  - sh: dotnet tool install --global FlubuCore.GlobalTool --version 5.0.3
  
  build_script:
  - sh: cd src
  - sh: flubu Rebuild.Linux
